### ISSUE TITLE
Footer w/ links to team info

### ISSUE THREAD

**Issue by pm-moyanor** [chingu-voyages/v46-tier2-team-22#21]
- [x] based on the figma build the structure
- [x] create links to repos and coders profiles
- [ ] use icons
- [ ] code font and colors from fonts and color pallette.

**Comment by Valeriusdev** [comment]
what kind of icons do I need to use?

**Comment by chef-louis** [comment]
@Valeriusdev [font-awesome github icon](https://fontawesome.com/icons/github?f=brands&s=solid) can work well for this

**Comment by Valeriusdev** [comment]
@chef-louis are they all free to use?

**Comment by pm-moyanor** [comment]
@Valeriusdev font-awesome offers one style free the rest have to pay, we can use the free one for this

**Comment by Valeriusdev** [comment]
Done
