### ISSUE TITLE
CARD-DETAILS (CSS) set fixed position in CardList

### ISSUE THREAD

**Issue by pm-moyanor** [chingu-voyages/v46-tier2-team-22#69]
The card opens at the top of the page, It would be nice to have it fixed in position over Cardlist section, to avoid scroll when close action

**Comment by chef-louis** [comment]
- [ ] Fix the position of the Card Detail component to diplay within the Cardlist component
- [ ] Gray background only within the Cardlist component
- [ ] Click anywhere outside the Card Detail component but within the Gray background to close the popup (in addition to the 'X' button)
